/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../web/schema.json
export type News = {
  _type: "news";
  title?: LocaleString;
  text?: LocaleBlockContent;
  link?: LinkExternal;
};

export type KeyVal = {
  _type: "keyVal";
  key?: LocaleString;
  value?: LocaleBlockContent;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Figure = {
  _type: "figure";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  caption?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Embed = {
  _type: "embed";
  title?: LocaleString;
  placeholder?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  url?: string;
  iframe?: string;
  aspectRatio?: string;
};

export type LocaleString = {
  _type: "localeString";
  fr?: string;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  metaImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type LinkIcon = {
  _type: "linkIcon";
  label?: string;
  link?: string;
  icon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type AtelierReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "atelier";
};

export type ProjectsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "projects";
};

export type ProjectReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "project";
};

export type HomeReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "home";
};

export type LinkInternal = {
  _type: "linkInternal";
  label?: LocaleString;
  link?:
    | AtelierReference
    | ProjectsReference
    | ProjectReference
    | HomeReference;
};

export type LinkExternal = {
  _type: "linkExternal";
  label?: string;
  link?: string;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "text-display-lg";
      listItem?: "bullet";
      markDefs?: Array<
        | {
            reference?:
              | AtelierReference
              | ProjectsReference
              | ProjectReference
              | HomeReference;
            _type: "linkInternal";
            _key: string;
          }
        | {
            href?: string;
            _type: "linkExternal";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type CardHome = {
  _type: "cardHome";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  project?: ProjectReference;
};

export type LocaleBlockContent = {
  _type: "localeBlockContent";
  fr?: BlockContent;
};

export type LocaleText = {
  _type: "localeText";
  fr?: string;
};

export type PageModulaire = {
  _id: string;
  _type: "pageModulaire";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  homePage?: boolean;
  title?: LocaleString;
  subTitle?: LocaleString;
  slug?: Slug;
  color?: Color;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  siteDescription?: LocaleString;
  siteDescriptions?: Array<
    {
      _key: string;
    } & LocaleString
  >;
  navPrimary?: Array<
    | ({
        _key: string;
      } & LinkInternal)
    | ({
        _key: string;
      } & LinkExternal)
  >;
  navSocial?: Array<
    {
      _key: string;
    } & LinkIcon
  >;
  navSecondary?: Array<
    | ({
        _key: string;
      } & LinkInternal)
    | ({
        _key: string;
      } & LinkExternal)
  >;
  baseline?: LocaleBlockContent;
  contact?: string;
  labelNewsletter?: LocaleString;
  msgNewsletter?: LocaleText;
  message404?: BlockContent;
  colors?: Array<
    {
      _key: string;
    } & Color
  >;
  customCss?: string;
};

export type Atelier = {
  _id: string;
  _type: "atelier";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  items?: Array<
    {
      _key: string;
    } & KeyVal
  >;
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  subTitle?: string;
  imageCover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  text?: LocaleBlockContent;
  type?: LocaleText;
  programme?: LocaleText;
  client?: string;
  team?: string;
  city?: string;
  zip?: string;
  numbers?: string;
  year?: string;
  metas?: Array<
    {
      _key: string;
    } & KeyVal
  >;
  related?: ProjectReference;
};

export type Home = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  projects?: Array<
    | ({
        _key: string;
      } & CardHome)
    | ({
        _key: string;
      } & ProjectReference)
  >;
  items?: Array<
    {
      _key: string;
    } & CardHome
  >;
  news?: Array<
    {
      _key: string;
    } & News
  >;
};

export type Projects = {
  _id: string;
  _type: "projects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  items?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | News
  | KeyVal
  | SanityImageAssetReference
  | Figure
  | SanityImageCrop
  | SanityImageHotspot
  | Embed
  | LocaleString
  | Seo
  | LinkIcon
  | AtelierReference
  | ProjectsReference
  | ProjectReference
  | HomeReference
  | LinkInternal
  | LinkExternal
  | BlockContent
  | CardHome
  | LocaleBlockContent
  | LocaleText
  | PageModulaire
  | Color
  | Slug
  | Settings
  | Atelier
  | Project
  | Home
  | Projects
  | RgbaColor
  | HsvaColor
  | HslaColor
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../web/app/sanity-api/sanity-queries.tsx
// Variable: SETTINGS_QUERY
// Query: *[_type == "settings"][0]{  ...,  navPrimary[]{    ...,    _type == 'linkInternal' => {      ...,      link->{        _type,        slug      }    }  },}
export type SETTINGS_QUERY_RESULT = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName?: string;
  siteDescription?: LocaleString;
  siteDescriptions?: Array<
    {
      _key: string;
    } & LocaleString
  >;
  navPrimary: Array<
    | {
        _key: string;
        _type: "linkExternal";
        label?: string;
        link?: string;
      }
    | {
        _key: string;
        _type: "linkInternal";
        label?: LocaleString;
        link:
          | {
              _type: "atelier";
              slug: Slug | null;
            }
          | {
              _type: "home";
              slug: Slug | null;
            }
          | {
              _type: "project";
              slug: Slug | null;
            }
          | {
              _type: "projects";
              slug: Slug | null;
            }
          | null;
      }
  > | null;
  navSocial?: Array<
    {
      _key: string;
    } & LinkIcon
  >;
  navSecondary?: Array<
    | ({
        _key: string;
      } & LinkExternal)
    | ({
        _key: string;
      } & LinkInternal)
  >;
  baseline?: LocaleBlockContent;
  contact?: string;
  labelNewsletter?: LocaleString;
  msgNewsletter?: LocaleText;
  message404?: BlockContent;
  colors?: Array<
    {
      _key: string;
    } & Color
  >;
  customCss?: string;
} | null;

// Source: ../web/app/sanity-api/sanity-queries.tsx
// Variable: HOME_QUERY
// Query: *[_type == "home"][0]{  ...,  seo{    	...,	metaImage{		asset->{			url		}	}  },  projects[]->{    	_id,  _type,  slug,  title,	programme,	year,	city,	zip,	numbers,	client,	imageCover{			asset->{		...,		altText,		title	}	}  },  items[]{    image{      	asset->{		...,		altText,		title	}    },    project->{      	_id,  _type,  slug,  title,	programme,	year,	city,	zip,	numbers,	client,	imageCover{			asset->{		...,		altText,		title	}	}    }  },  news[]{    ...  }}
export type HOME_QUERY_RESULT = {
  _id: string;
  _type: "home";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: {
    _type: "seo";
    metaTitle?: string;
    metaDescription?: string;
    metaImage: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
  title?: LocaleString;
  slug?: Slug;
  projects: Array<null | {
    _id: string;
    _type: "project";
    slug: Slug | null;
    title: LocaleString | null;
    programme: LocaleText | null;
    year: string | null;
    city: string | null;
    zip: string | null;
    numbers: string | null;
    client: string | null;
    imageCover: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title: string | null;
        description?: string;
        altText: string | null;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
    } | null;
  }> | null;
  items: Array<{
    image: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title: string | null;
        description?: string;
        altText: string | null;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
    } | null;
    project: {
      _id: string;
      _type: "project";
      slug: Slug | null;
      title: LocaleString | null;
      programme: LocaleText | null;
      year: string | null;
      city: string | null;
      zip: string | null;
      numbers: string | null;
      client: string | null;
      imageCover: {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title: string | null;
          description?: string;
          altText: string | null;
          sha1hash?: string;
          extension?: string;
          mimeType?: string;
          size?: number;
          assetId?: string;
          uploadId?: string;
          path?: string;
          url?: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
      } | null;
    } | null;
  }> | null;
  news: Array<{
    _key: string;
    _type: "news";
    title?: LocaleString;
    text?: LocaleBlockContent;
    link?: LinkExternal;
  }> | null;
} | null;

// Source: ../web/app/sanity-api/sanity-queries.tsx
// Variable: PROJECT_QUERY
// Query: *[_type == "project" && slug.current == $slug][0]{    ...,    seo{      	...,	metaImage{		asset->{			url		}	}    },    imageCover{      	asset->{		...,		altText,		title	}    },    images[]{      	asset->{		...,		altText,		title	}    },    fiche_technique[]{      ...    },    related->{      _type,      slug,      imageCover{        	asset->{		...,		altText,		title	}      }    }  }
export type PROJECT_QUERY_RESULT = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: {
    _type: "seo";
    metaTitle?: string;
    metaDescription?: string;
    metaImage: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
  title?: LocaleString;
  slug?: Slug;
  subTitle?: string;
  imageCover: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title: string | null;
      description?: string;
      altText: string | null;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  } | null;
  images: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title: string | null;
      description?: string;
      altText: string | null;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  }> | null;
  text?: LocaleBlockContent;
  type?: LocaleText;
  programme?: LocaleText;
  client?: string;
  team?: string;
  city?: string;
  zip?: string;
  numbers?: string;
  year?: string;
  metas?: Array<
    {
      _key: string;
    } & KeyVal
  >;
  related: {
    _type: "project";
    slug: Slug | null;
    imageCover: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title: string | null;
        description?: string;
        altText: string | null;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
    } | null;
  } | null;
  fiche_technique: null;
} | null;

// Source: ../web/app/sanity-api/sanity-queries.tsx
// Variable: ALL_PROJECTS_QUERY
// Query: *[_type == "project"]{    ...  }
export type ALL_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo?: Seo;
  title?: LocaleString;
  slug?: Slug;
  subTitle?: string;
  imageCover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  text?: LocaleBlockContent;
  type?: LocaleText;
  programme?: LocaleText;
  client?: string;
  team?: string;
  city?: string;
  zip?: string;
  numbers?: string;
  year?: string;
  metas?: Array<
    {
      _key: string;
    } & KeyVal
  >;
  related?: ProjectReference;
}>;

// Source: ../web/app/sanity-api/sanity-queries.tsx
// Variable: PROJECTS_QUERY
// Query: *[_type == "projects"][0]{  ...,  seo{    	...,	metaImage{		asset->{			url		}	}  },  items[]->{    	_id,  _type,  slug,  title,	programme,	year,	city,	zip,	numbers,	client,	imageCover{			asset->{		...,		altText,		title	}	}  }}
export type PROJECTS_QUERY_RESULT = {
  _id: string;
  _type: "projects";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: {
    _type: "seo";
    metaTitle?: string;
    metaDescription?: string;
    metaImage: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
  title?: LocaleString;
  slug?: Slug;
  items: Array<{
    _id: string;
    _type: "project";
    slug: Slug | null;
    title: LocaleString | null;
    programme: LocaleText | null;
    year: string | null;
    city: string | null;
    zip: string | null;
    numbers: string | null;
    client: string | null;
    imageCover: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title: string | null;
        description?: string;
        altText: string | null;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
    } | null;
  }> | null;
} | null;

// Source: ../web/app/sanity-api/sanity-queries.tsx
// Variable: ATELIER_QUERY
// Query: *[_type == "atelier"][0]{  ...,  seo{    	...,	metaImage{		asset->{			url		}	}  },  images[]{    	asset->{		...,		altText,		title	}  },  items[]{    ...  }}
export type ATELIER_QUERY_RESULT = {
  _id: string;
  _type: "atelier";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  seo: {
    _type: "seo";
    metaTitle?: string;
    metaDescription?: string;
    metaImage: {
      asset: {
        url: string | null;
      } | null;
    } | null;
  } | null;
  title?: LocaleString;
  slug?: Slug;
  images: Array<{
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title: string | null;
      description?: string;
      altText: string | null;
      sha1hash?: string;
      extension?: string;
      mimeType?: string;
      size?: number;
      assetId?: string;
      uploadId?: string;
      path?: string;
      url?: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
  }> | null;
  items: Array<{
    _key: string;
    _type: "keyVal";
    key?: LocaleString;
    value?: LocaleBlockContent;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"settings\"][0]{\n  ...,\n  navPrimary[]{\n    ...,\n    _type == 'linkInternal' => {\n      ...,\n      link->{\n        _type,\n        slug\n      }\n    }\n  },\n}": SETTINGS_QUERY_RESULT;
    '*[_type == "home"][0]{\n  ...,\n  seo{\n    \n\t...,\n\tmetaImage{\n\t\tasset->{\n\t\t\turl\n\t\t}\n\t}\n\n  },\n  projects[]->{\n    \n\t_id,\n  _type,\n  slug,\n  title,\n\tprogramme,\n\tyear,\n\tcity,\n\tzip,\n\tnumbers,\n\tclient,\n\timageCover{\n\t\t\n\tasset->{\n\t\t...,\n\t\taltText,\n\t\ttitle\n\t}\n\n\t}\n\n  },\n  items[]{\n    image{\n      \n\tasset->{\n\t\t...,\n\t\taltText,\n\t\ttitle\n\t}\n\n    },\n    project->{\n      \n\t_id,\n  _type,\n  slug,\n  title,\n\tprogramme,\n\tyear,\n\tcity,\n\tzip,\n\tnumbers,\n\tclient,\n\timageCover{\n\t\t\n\tasset->{\n\t\t...,\n\t\taltText,\n\t\ttitle\n\t}\n\n\t}\n\n    }\n  },\n  news[]{\n    ...\n  }\n}': HOME_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0]{\n    ...,\n    seo{\n      \n\t...,\n\tmetaImage{\n\t\tasset->{\n\t\t\turl\n\t\t}\n\t}\n\n    },\n    imageCover{\n      \n\tasset->{\n\t\t...,\n\t\taltText,\n\t\ttitle\n\t}\n\n    },\n    images[]{\n      \n\tasset->{\n\t\t...,\n\t\taltText,\n\t\ttitle\n\t}\n\n    },\n    fiche_technique[]{\n      ...\n    },\n    related->{\n      _type,\n      slug,\n      imageCover{\n        \n\tasset->{\n\t\t...,\n\t\taltText,\n\t\ttitle\n\t}\n\n      }\n    }\n  }\n': PROJECT_QUERY_RESULT;
    '\n  *[_type == "project"]{\n    ...\n  }\n': ALL_PROJECTS_QUERY_RESULT;
    '*[_type == "projects"][0]{\n  ...,\n  seo{\n    \n\t...,\n\tmetaImage{\n\t\tasset->{\n\t\t\turl\n\t\t}\n\t}\n\n  },\n  items[]->{\n    \n\t_id,\n  _type,\n  slug,\n  title,\n\tprogramme,\n\tyear,\n\tcity,\n\tzip,\n\tnumbers,\n\tclient,\n\timageCover{\n\t\t\n\tasset->{\n\t\t...,\n\t\taltText,\n\t\ttitle\n\t}\n\n\t}\n\n  }\n}': PROJECTS_QUERY_RESULT;
    '*[_type == "atelier"][0]{\n  ...,\n  seo{\n    \n\t...,\n\tmetaImage{\n\t\tasset->{\n\t\t\turl\n\t\t}\n\t}\n\n  },\n  images[]{\n    \n\tasset->{\n\t\t...,\n\t\taltText,\n\t\ttitle\n\t}\n\n  },\n  items[]{\n    ...\n  }\n}': ATELIER_QUERY_RESULT;
  }
}
